# Generated by Django 5.1.2 on 2024-11-18 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('travel', '여행'), ('hobby_culture', '취미/문화'), ('health_exercise', '건강/운동'), ('spending_saving_donating', '소비/저축/기부'), ('self_development', '자기계발'), ('others', '기타'), ('career', '커리어'), ('family_friends', '가족/친구')], max_length=50)),
                ('motive', models.TextField()),
                ('period', models.CharField(choices=[('long_term', 'Long Term'), ('short_term', 'Short Term')], max_length=10)),
                ('is_achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=255)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='bucketlists.bucketlist')),
            ],
        ),
    ]
