# Generated by Django 5.1.2 on 2024-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
