# Generated by Django 5.1.2 on 2024-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0002_goal_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='duration_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
